### ISSUE TITLE
Support basePath option

### ISSUE THREAD

**Issue by remcokranenburg** [marcules/karma-remap-istanbul#1]
If you put your compiled files in a different folder than your source files, you need to set the base path to the original location so remap-istanbul can find the files.

**Comment by marcules** [comment]
Hello @Remco47 

this is true, but has not directly to do with the plugin itself. You just have to set the sourceRoot when you write the sourcemaps to the correct location, for it to be rewritten to the correct files, which then can be found by remap-istanbul.

In my setup we have the typescript sourcefiles in `/src/app/` and the compiled js-sources in `/.tmp/serve/app/`. With this configuration the mapping is being generated correctly:

``` js
.pipe($.sourcemaps.write('.', { includeContent: false, sourceRoot: path.join(__dirname, '/../src/app') }))
```

``` js
gulp.task('scripts', ['tsd:link'], function () {
  mkdirp.sync(conf.paths.tmp);

  return gulp.src(path.join(conf.paths.src, '/app/**/*.ts'))
    .pipe($.sourcemaps.init())
    .pipe($.tslint())
    .pipe($.tslint.report('prose', { emitError: false }))
    .pipe($.typescript({ sortOutput: true, target: 'ES5' })).on('error', conf.errorHandler('TypeScript'))
    .pipe($.sourcemaps.write('.', { includeContent: false, sourceRoot: path.join(__dirname, '/../src/app') }))
    .pipe($.toJson({ filename: path.join(conf.paths.tmp, '/sortOutput.json'), relative: true }))
    .pipe(devConfig.replace())
    .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/app')))
    .pipe(browserSync.reload({ stream: true  }))
    .pipe($.size());
});
```

I hope I understood your request correctly, and this solves your problem.

**Comment by mattlewis92** [comment]
I don't think there's anything actionable here, the solution provided [here](https://github.com/marcules/karma-remap-istanbul/issues/1#issuecomment-194831167) should be enough, so I'm going to close this for now.
