### ISSUE TITLE
Doubled error message

### ISSUE THREAD

**Issue by unlight** [marcules/karma-remap-istanbul#23]
Part of the `karma.config`:

```
reporters: ["progress", "coverage", "karma-remap-istanbul"],
```

```
SlimerJS App component should build without a problem FAILED
        Failed: fixture.nativeElement.innerText is undefined
        @build/js/components/app/components/app/app.component.spec.ts:25:16 <- build/js/components/app/app.component.spec.js:22:13
SlimerJS: Executed 8 of 14 (1 FAILED) (skipped 1) (0 secs / 0.268 secs)
SlimerJS App component should build without a problem FAILED
        Failed: fixture.nativeElement.innerText is undefined
SlimerJS: Executed 8 of 14 (1 FAILED) (skipped 6) (0.283 secs / 0.268 secs)
```

If I will remove `karma-remap-istanbul` from `reporters`, the result will be:

```
SlimerJS App component should build without a problem FAILED
        Failed: fixture.nativeElement.innerText is undefined
        @build/js/components/app/components/app/app.component.spec.ts:25:16 <- build/js/components/app/app.component.spec.js:22:13
SlimerJS: Executed 8 of 14 (1 FAILED) (skipped 6) (0.315 secs / 0.263 secs)
```

**Comment by unlight** [comment]
Workaround - separated gulp task.

``` js
    var remapIstanbul = require("remap-istanbul/lib/gulpRemapIstanbul");
    gulp.task("coverage", function() {
        return gulp.src(".coverage/**/coverage.json")
            .pipe(remapIstanbul({
                basePath: "./",
                reports: {
                    "html": ".coverage/html-report",
                    "json": ".coverage/report.json",
                    "lcovonly": ".coverage/lcov-report.info"
                }
            }));
    });
```

**Comment by mattlewis92** [comment]
I think the issue here was that karma-coverage is not actually needed when using this lib, using `reporters: ["progress", "karma-remap-istanbul"]` and adding the reporters in the karma.conf.js like so:
```
remapIstanbulReporter: {
      reports: {
        html: 'coverage/html',
        'text-summary': null
      }
    },
```
should be enough to prevent the double output. If this doesn't work for you please let me know!

**Comment by Necroskillz** [comment]
Hi,

I also have this issue. I only have `progress` and `karma-remap-istanbul` as reporters. I have similar setup as this project: https://github.com/gund/ng-http-interceptor and it also happens there.

**Comment by mattlewis92** [comment]
I don't have time to actually test it, but try setting this to only instrument .ts files: https://github.com/gund/ng-http-interceptor/blob/master/webpack.config.js#L65 and remove the inline sourcemap option as it's already handled by the SourceMapDevToolPlugin below: https://github.com/gund/ng-http-interceptor/blob/master/webpack.config.js#L8

Alternatively try using [this loader](https://github.com/deepsweet/istanbul-instrumenter-loader) with [this reporter](https://github.com/mattlewis92/karma-coverage-istanbul-reporter) instead of sourcemap-istanbul-instrumenter-loader and karma-remap-istanbul.

**Comment by Necroskillz** [comment]
I tried all of your suggestions, but none of them seem to have any effect on the doubled failed test reporting.

**Comment by mattlewis92** [comment]
Oh maybe it's because of the entry in the webpack config, this isn't required if using karma-webpack, try deleting this: https://github.com/gund/ng-http-interceptor/blob/master/webpack.config.js#L14-L16

**Comment by Necroskillz** [comment]
It isn't required - but removing it again has no effect :P
