### ISSUE TITLE
Feature: Exclude files from coverage

### ISSUE THREAD

**Issue by marc-ferrer** [marcules/karma-remap-istanbul#26]
It will be useful to be able to exclude certain files from coverage.

Both, istanbul and remap-istanbul accept the exclude option, but the any configuration of this library is not passed to them.

I'm working on it, in case I can find out a way to do it properly (which I'm not sure at this moment), it would be ok to make a pull request?

**Comment by mattlewis92** [comment]
It should now be possible to do this in 0.3.0. In your karma config pass:
```
remapIstanbulReporter: {
    remapOptions: {
      exclude: 'string/regex/function'
    }
  }
```

Hope that helps! 😃

**Comment by PikaChokeMe** [comment]
Does this allow full filepaths? 
I'm using karma-remap-instanbul 0.4.0 
with
angular-cli: 1.0.0-beta.25.5
node: 6.9.1
os: win32 x64

I've tried 
```
remapOptions: {
        exclude: './src/app/path/to/my/fileToExclude.ts'
      },
```
But this doesn't actually seem to achieve anything and running
`ng test --code-coverage` still fails for low code coverage on this file.

**Comment by mattlewis92** [comment]
It should do looking at the [source of remap-istanbul](https://github.com/SitePen/remap-istanbul/blob/master/src/CoverageTransformer.js#L18-L26) - perhaps try without the leading `./` i.e. `exclude: 'src/app/path/to/my/fileToExclude.ts'`

**Comment by PikaChokeMe** [comment]
I just tried using 

```
remapOptions: {
  exclude: './src/app/core/services/guard-services/iframe-unload-guard-service.ts'
},
```

```
remapOptions: {
  exclude: 'src/app/core/services/guard-services/iframe-unload-guard-service.ts'
},
```
and
```
remapOptions: {
  exclude: 'app/core/services/guard-services/iframe-unload-guard-service.ts'
},
```

which is actually consistent with the 
`Low Coverage: app/core/services/guard-services/iframe-unload-guard-service.ts 24.24% of 75% lines`
Error I receive, 
but none of them work.

**Comment by mattlewis92** [comment]
As a basic test to see if anything is working can you try `exclude: /iframe-unload-guard-service/`. Are you also on the latest version of this module?

**Comment by PikaChokeMe** [comment]
I just tried 
`exclude: '/iframe-unload-guard-service/'` and it does not work.

package.json reports
`"karma-remap-istanbul": "0.4.0",`


My entire `karma.conf.js` is as follows:
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', 'angular-cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-remap-istanbul'),
      require('angular-cli/plugins/karma'),
      require('karma-istanbul-threshold')
    ],
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['angular-cli']
    },
    mime: {
      'text/x-typescript': ['ts','tsx']
    },
    remapIstanbulReporter: {
      remapOptions: {
        exclude: '/iframe-unload-guard-service/'
      },
      reports: {
        html: './coverage',
        json: './coverage/coverage-report.json'
      }
    },
    istanbulThresholdReporter: {
      src: './coverage/coverage-report.json',
      basePath: './src',
      reporters: ['text'],
      thresholds: {
        global: {
          statements: 0,
          branches: 0,
          lines: 75,
          functions: 0
        },
        each: {
          statements: 0,
          branches: 0,
          lines: 75,
          functions: 0
        }
      }
    },
    angularCli: {
      config: './angular-cli.json',
      environment: 'dev'
    },
    reporters: config.angularCli && config.angularCli.codeCoverage
      ? ['progress', 'karma-remap-istanbul', 'istanbul-threshold']
      : ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

Perhaps I am missing something really simple or dumb?

**Comment by PikaChokeMe** [comment]
Nevermind! 

I see that you didn't include `'` around `exclude: /iframe-unload-guard-service/` I have tried this and it works!
I wouldn't have thought that the `'` were unnecessary for regex

**Comment by mattlewis92** [comment]
Ah I didn't spot the quotes either, glad you got it sorted 😃

**Comment by PikaChokeMe** [comment]
So does this not work with quoted filepaths? just regex strings delimited with `/` ?

**Comment by mattlewis92** [comment]
It does work with strings as the tests demonstrate: https://github.com/marcules/karma-remap-istanbul/blob/master/test/index.spec.js#L76 

I'm not sure exactly what file path it is actually tested on though, I would have thought it was the full path but maybe its just the filename?

**Comment by marc-ferrer** [comment]
I did not have the time to try this until now. Looks great!
I would have expected to be able to use an array of strings to exclude multiple files, but this has an easy workaround using a function.

@BustyLoli-Chan it does work with quoted paths but you have to specify the relative path without a leading `./`

**Comment by marc-ferrer** [comment]
Is there any reason why the exclude with a function should not work with version `0.4.0`?

**Comment by mattlewis92** [comment]
It was only added in `0.8.0` of remap-istanbul and this module is still on `^0.6.4`. There was a bug introduced in `0.7.0` that broke this module for some people, I sent a PR to remap-istanbul to get it fixed that has now been merged, as soon as they cut a new release with it I'll upgrade the remap-istanbul dependency to latest in this module. In the meantime you could use 0.3.0 of this lib instead which has the upgraded remap-istanbul dependency.

**Comment by luoyaqifei** [comment]
Hi, it seems they have released the version 0.9.0 now, could you kindly upgrade to it in the lib folder and fix the "No element indexed by 1" in v0.3.0? Thanks!

**Comment by mattlewis92** [comment]
@luoyaqifei thanks for the heads up! Released as 0.6.0

**Comment by cancio** [comment]
@marc-ferrer can you share your workaround for a way to exclude multiple files? I was hoping to be able to provide a list of files.

**Comment by marc-ferrer** [comment]
@cancio Sure. What I did was create a function that checks if the file is present in a array of files to be excluded.

```
remapOptions: {
  exclude: function (path) {
    // Although this are not absolute paths, the leading slash is important.
    // These paths are relative to the karma.conf location.
    const EXCLUDED_FILES = [
      '/path/to/a/file',
      '/path/to/another/file'
    ];
    return EXCLUDED_FILES.indexOf(path.substring(__dirname.length)) >= 0;
  }
}
```

Just the first thing that came to my mind to be able to provide an array of files... Let me know if you end up with a cleaner code.
