### ISSUE TITLE
Doesn't work in the first/fresh run

### ISSUE THREAD

**Issue by pablodenadai** [marcules/karma-remap-istanbul#3]
Hi ya, when I run karma for the first time the following message is printed in the console: `Couldn't find any specified files, exiting without doing anything.`

Then, if I attempt to run it again, I get:  `Not all files specified in sources could be found, continue with partial remapping.`. Which is okay for now (only the files with spec are included in coverage).

So. It looks like that there's a race condition going on here where the file `coverage.json` hasn't yet been create during the first run.

Does it make sense?

**Comment by pablodenadai** [comment]
I increased the timeouts to 5secs.

```
timeoutNotCreated: 5000,
timeoutNoMoreFiles: 5000
```

I can see it's waiting and the file is created but it still fails and prints the message `Couldn't find any specified files, exiting without doing anything.`.

**Comment by pablodenadai** [comment]
I believe the issue is related to this ticket in Chokidar https://github.com/paulmillr/chokidar/issues/462.

**Comment by pablodenadai** [comment]
Hi @marcules I'd like to put a PR forward to fix this issue. Could you please let me know if you're actively working on this project? Otherwise I'll just fork it. Thanks.

**Comment by marcules** [comment]
hi @ghpabs I'm currently under a high workload, so I won't be able to fix anything in the near future, I'll merge in PRs if they come though

**Comment by pablodenadai** [comment]
Cool thanks for the update @marcules. There's not pressure to merge this PR if you're not comfortable with it. Once again, I can always go with a fork instead. :-)

**Comment by oocx** [comment]
@marcules can you please merge this PR? Without this change, I always get a "Couldn't find any specified files, exiting without doing anything" error.

**Comment by pablodenadai** [comment]
Hi @oocx unfortunately the PR (#4) had some flaws and we decided not to go ahead with it.

**Comment by pablodenadai** [comment]
I'll leave the GitHub ticket open as it's effectively an bug in the plugin - but the PR mentioned above is no good.

**Comment by oocx** [comment]
The PR4 currently works for me, the master branch doesn't. I'm currently referencing the github repo for the PR directly in my package json ("karma-remap-istanbul": "https://github.com/ghpabs/karma-remap-istanbul").

Are you working on an alternative solution?

**Comment by pablodenadai** [comment]
> Are you working on an alternative solution?

No. I used two different Gulp tasks instead. See `angular2-seed-project` in my GitHub page.

**Comment by delasteve** [comment]
Should be fixed in `0.2.1`.
