### ISSUE TITLE
include all files in coverage?

### ISSUE THREAD

**Issue by shaikhspear16** [marcules/karma-remap-istanbul#34]
All the files are not included in the coverage report. Only files having corresponding .spec files are shows in the report.

`includeAllSources: true` 
of karma-coverage library does not work.
```

 remapIstanbulReporter: {
      reports: {
        html: 'coverage'
      },
      includeAllSources: true
    },
```

**Comment by mattlewis92** [comment]
Can you share a repo that reproduces your problem? There are so many different ways of configuring this module it's pretty much impossible to know what's going wrong otherwise.

**Comment by shaikhspear16** [comment]
https://github.com/shaikhspear16/hello-world
is my repo. (please unzip app folder, first time creating a repo)

only app.component.ts file is there in the coverage report.

Query:
I have added a key "outDir" in tsconfig file so that my development folder is clean with typescript files and no unnecessary map and js files are present. After doing so, none of my rest cases run and a blank report is generated. Can you please help me with the configuration changes in karma.config.js to run test cases and generate coverage report from it.

**Comment by ringodotnl** [comment]
Same issue here only .ts files with .spec.ts files are covered in the coverage.

Config karma.conf.js:

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', 'angular-cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-phantomJS-launcher'),
      require('karma-remap-istanbul'),
      require('angular-cli/plugins/karma'),
      require('karma-nyan-reporter'),
    ],
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['angular-cli']
    },
    remapIstanbulReporter: {
      reports: {
        html: 'coverage',
        lcovonly: './coverage/coverage.lcov',
      },
      reportOptions: {
        includeAllSources: true
      }
    },
    angularCli: {
      config: './angular-cli.json',
      environment: 'mock'
    },
    coverageReporter: {
      includeAllSources: true
    },
    // optional try out mocha
    reporters: ['nyan', 'karma-remap-istanbul'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    // optional add Chrome
    browsers: ['PhantomJS'],
    singleRun: false
  });
};


Running the unit test with:
ng test --code-coverage

**Comment by SDohle** [comment]
Is this issued fixed?

**Comment by cloudscape-germany** [comment]
Same issue. Renders the whole coverage completely useless, since we always get dream phantasy results, like 95%, but real coverage is like 4%. Please somebody fix !

**Comment by jonbonraki** [comment]
I have the same issue, is there any progress on this?
