### ISSUE TITLE
v0.4.0 Can't find sourcemap anymore

### ISSUE THREAD

**Issue by paulsouche** [marcules/karma-remap-istanbul#35]
Hi,

Updating to 0.4.0 cause an issue with sourcemap and remap-istanbul. This [commit](50c7e4c24ff6020fffc9d08087dd21b261bf40c8) downgrade the version to 0.6.x and cause this [issue](https://github.com/SitePen/remap-istanbul/issues/41) to pop up.

Downgrading to 0.3.2 worked for me.

Thx

**Comment by mattlewis92** [comment]
The upgrade to the latest remap Istanbul version broke things for some people hence why I downgraded it. I sent a PR to remap-Istanbul with a fix but it's not yet been merged: https://github.com/SitePen/remap-istanbul/pull/120

Once that's merged I will upgrade remap Istanbul and cut a new release. For now you'll just need to stay on 0.3.x if that works for you.
