### ISSUE TITLE
[Bug] Could not find sourcemap for ts file

### ISSUE THREAD

**Issue by luchillo17** [marcules/karma-remap-istanbul#36]
** Bug report **
I'm making a Node app with typescript and webpack, it was working fine with the `istanbul-instrumenter-loader` and the `coverage` reporter, however when i added this repo it breaks like so:

```ts
Error: Could not find source map for: "/Users/aplicaciones2/Documents/tao-graphql-api/src/server.ts"
```

** Config file **
```ts
// karma.conf.ts
import webpackConfig from './config/webpack.test'; // the settings that are common to prod and dev
// import karma from 'karma';

const srcGlob = 'src/**/!(*.spec|*.d).ts';
const testGlob = 'src/**/*.spec.ts';
const webpackEnv = { env: 'test' };

export default (config) => {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // Fix for typescript mime type to send ts files to browser for testing
    mime : {
      'text/x-typescript': [
        'ts',
        'tsx'
      ]
    },

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine', 'source-map-support'],

    // list of files / patterns to load in the browser
    files: [
      // srcGlob,
      // './node_modules/core-js/index.js',
      testGlob
    ],

    // list of files to exclude
    exclude: [
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      // [srcGlob]: [ 'webpack', 'sourcemap', 'coverage' ],
      // './node_modules/core-js/index.js': [ 'webpack', ],
      [testGlob]: [ 'webpack', 'sourcemap' ],
    },

    webpack: webpackConfig(webpackEnv),
    webpackMiddleware: {noInfo: true},

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    // reporters: ['progress'],
    reporters: ['progress', 'notification', 'coverage', 'karma-remap-istanbul'],
    // reporters: ['progress', 'notification', 'coverage'],
    // coverageReporter: {
    //   dir: 'coverage/',
    //   instrumenterOptions: {
    //     istanbul: { noCompact: false }
    //   },
    //   reporters: [
    //     { type: 'lcov', subdir: '.' },
    //     { type: 'json', subdir: '.' },
    //     { type: 'text-summary' },
    //   ],
    // },
    remapIstanbulReporter: {
      reports: {
        html: 'coverage'
      }
    },

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values:
      // config.LOG_DISABLE ||
      // config.LOG_ERROR ||
      // config.LOG_WARN ||
      // config.LOG_INFO ||
      // config.LOG_DEBUG
    logLevel: config.LOG_INFO,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: false,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['NodeWebkit'],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  });
};
```

**Comment by mattlewis92** [comment]
You have a couple of options if you're using webpack. You can either stick with this module and use the `sourcemap-istanbul-instrumenter-loader` instead of the `istanbul-instrumenter-loader`. Full example here: https://github.com/marcules/karma-remap-istanbul/blob/master/examples/webpack/karma.conf.js

Alternatively don't use this module, stick with the `istanbul-instrumenter-loader` and just use this reporter instead of karma-coverage: https://github.com/mattlewis92/karma-coverage-istanbul-reporter Personally I'm inclined to go down this route as it uses the latest supported istanbul 1.x APIs, remap-istanbul is built on the older istanbul 0.4.x lib which doesn't get much activity anymore.

Hope that helps! 😄

**Comment by luchillo17** [comment]
@mattlewis92 Amazing, exactly what i needed, not just it works but it now shows the called line and numbers correctly, before it was showing them in the `lcov` report moved up.

I ended up using the 2º route, i tough i would have to wait a lot for an answer, but you gave me the solution right away, thanks.

Btw is there a way to tell the reporters chosen to take different folders? right now if i put `json-summary`, `lcov`, and `html`, it seems only the `lcov` one takes it's own folder and the other 2 goes in the base `dir` for the `coverageIstanbulReporter`.

Also having trouble making the test works when importing `core-js`, any idea? [karma-webpack#219](https://github.com/webpack-contrib/karma-webpack/issues/219)

**Comment by mattlewis92** [comment]
The options in the karma reporter are passed directly to istanbul, so you can use these to control the location of the reports: https://github.com/istanbuljs/istanbul-api/blob/master/lib/config.js#L34-L38

**Comment by luchillo17** [comment]
But it seems like each report chooses it's own folder, i know i can set the root reports folder, however the subfolder for each report idk if it's possible.

**Comment by mattlewis92** [comment]
You can use the `report-config` option:

```
coverageIstanbulReporter: {
  'report-config': {
    html: {
      subdir: 'html'
   }
  }
}
```

Each reporter has its own options, so you'll need to read the source of the reports to see what each reporters options are (ctrl + f for `opts`): https://github.com/istanbuljs/istanbul-reports/tree/master/lib

**Comment by luchillo17** [comment]
Nice, now i just lack a way to tell karma to restart my transpiled express server between each run (each time i save a file).

**Comment by luchillo17** [comment]
@mattlewis92 does `report-config` replaces the `reports` array?

**Comment by mattlewis92** [comment]
I think you need to use both like so:
```
coverageIstanbulReporter: {
  reports: ['html'],
  'report-config': {
    html: {
      subdir: 'html'
   }
  },
  fixWebpackSourcePaths: true
}
```
